
name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build IPA
        run: |
          mkdir -p output
          xcodebuild -scheme AnniversaryTimerApp -sdk iphoneos -configuration Release -destination 'generic/platform=iOS' clean build CODE_SIGNING_ALLOWED=NO
          xcodebuild -scheme AnniversaryTimerApp -sdk iphoneos -configuration Release -archivePath output/AnniversaryTimerApp.xcarchive archive CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath output/AnniversaryTimerApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath output

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: AnniversaryTimerApp
          path: output/*.ipa
