name: Build IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: Build archive
      run: |
        xcodebuild -scheme YourAppName -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/YourApp.xcarchive \
          -exportPath $PWD/build/ipa \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: iOS-App
        path: build/ipa/*.ipa
