name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Build App
        run: |
          fastlane gym --workspace LoveAnniversaryApp.xcworkspace \
                       --scheme LoveAnniversaryApp \
                       --export_method development
